@url = http://localhost:5000/surveyors-module

@surveyorId = 

@surveyorEmail = user@gmail.com

###
GET {{url}}

###
GET {{url}}/{{surveyorId}}

###
POST {{url}}/surveyors
Content-Type: application/json

{
    "email": "ce@gmail.com",
    "firstName": "Ce",
    "surname": "Zu",
    "position": "surveyor"
}

###
POST {{url}}/surveyors/{{surveyorEmail}}
Content-Type: application/json

{
    "firstName": "Cez",
    "surname": "Zuk",
    "position": "land surveyor"
}