@url = http://localhost:5000/surveyors-module

@surveyorId = 1986694d-4f2f-426e-808a-da9d36ae7dc0

@surveyorEmail = user@gmail.com

###
GET {{url}}

###
GET {{url}}/{{surveyorId}}

###
POST {{url}}/surveyors
Content-Type: application/json

{
    "email": "user@gmail.com",
    "firstName": "user",
    "surname": "user",
    "position": "surveyor"
}

###
POST {{url}}/surveyors/{{surveyorEmail}}
Content-Type: application/json

{
    "firstName": "johny",
    "surname": "john",
    "position": "land surveyor"
}

###
POST {{url}}/surveyors/backdoor/create
Content-Type: application/json

{
    "email": "test2@gmail.com",
    "firstName": "johny",
    "surname": "bonny",
    "position": "land surveyor"
}

###
POST {{url}}/surveyors/backdoor/create
Content-Type: application/json

{
    "id": "{{surveyorId}}"
}

###
GET {{url}}/surveyors/get
Content-Type: application/json

{
    "id": "{{surveyorId}}"
}