@url = http://localhost:5000/surveyors-module

@surveyorId = 1986694d-4f2f-426e-808a-da9d36ae7dc0

@surveyorEmail = user@gmail.com

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YThiNWU4NjYxNjg0N2U2OTJhYjFmMTFhMGU2M2MzYiIsInVuaXF1ZV9uYW1lIjoiNWE4YjVlODY2MTY4NDdlNjkyYWIxZjExYTBlNjNjM2IiLCJqdGkiOiIxYmFmMzJkMC04YjlkLTRjNzQtYWViNC00YzcyNjJiNTU3MTIiLCJpYXQiOiIxNzE2OTIxODk3MDE3IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsInBlcm1pc3Npb25zIjpbInN0b3JlcyIsInVzZXJzIiwic3VydmV5b3JzIiwiZXF1aXBtZW50IiwiY29sbGVjdGlvbnMiLCJjYWxpYnJhdGlvbnMiLCJzYWdhIl0sIm5iZiI6MTcxNjkyMTg5NywiZXhwIjoxNzE3MDA0Njk3LCJpc3MiOiJzdXJ2ZXlzdG9yZSJ9.nkVybSQT5475CRiM4UryRjVNavlHGrcTvSxIVOltgqw

###
GET {{url}}

###
GET {{url}}/{{surveyorId}}

###
POST {{url}}/surveyors
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "firstName": "Jon",
    "surname": "Brw",
    "position": "surveyor"
}

###
POST {{url}}/surveyors/{{surveyorEmail}}
Content-Type: application/json

{
    "firstName": "johny",
    "surname": "john",
    "position": "land surveyor"
}

###
POST {{url}}/surveyors/backdoor/create
Content-Type: application/json

{
    "email": "test2@gmail.com",
    "firstName": "johny",
    "surname": "bonny",
    "position": "land surveyor"
}

###
POST {{url}}/surveyors/backdoor/create
Content-Type: application/json

{
    "id": "{{surveyorId}}"
}

###
GET {{url}}/surveyors/get
Content-Type: application/json

{
    "id": "{{surveyorId}}"
}