// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SurveyStore.Modules.Collections.Infrastructure.EF;

namespace SurveyStore.Modules.Collections.Infrastructure.EF.Migrations
{
    [DbContext(typeof(CollectionsDbContext))]
    [Migration("20240630085306_AddDateToCollections")]
    partial class AddDateToCollections
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("collections")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SurveyStore.Modules.Collections.Domain.Collections.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CollectionStoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReturnStoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("SurveyEquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SurveyorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurveyEquipmentId");

                    b.HasIndex("SurveyorId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("SurveyStore.Modules.Collections.Domain.Collections.Entities.Kit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Kit");
                });

            modelBuilder.Entity("SurveyStore.Modules.Collections.Domain.Collections.Entities.KitCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CollectionStoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("KitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReturnStoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("SurveyorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KitId");

                    b.HasIndex("SurveyorId");

                    b.ToTable("KitCollections");
                });

            modelBuilder.Entity("SurveyStore.Modules.Collections.Domain.Collections.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("SurveyStore.Modules.Collections.Domain.Collections.Entities.SurveyEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SurveyEquipment");
                });

            modelBuilder.Entity("SurveyStore.Modules.Collections.Domain.Collections.Entities.Surveyor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Surveyors");
                });

            modelBuilder.Entity("SurveyStore.Modules.Collections.Domain.Collections.Entities.Collection", b =>
                {
                    b.HasOne("SurveyStore.Modules.Collections.Domain.Collections.Entities.SurveyEquipment", "SurveyEquipment")
                        .WithMany()
                        .HasForeignKey("SurveyEquipmentId");

                    b.HasOne("SurveyStore.Modules.Collections.Domain.Collections.Entities.Surveyor", "Surveyor")
                        .WithMany("Collections")
                        .HasForeignKey("SurveyorId");

                    b.Navigation("SurveyEquipment");

                    b.Navigation("Surveyor");
                });

            modelBuilder.Entity("SurveyStore.Modules.Collections.Domain.Collections.Entities.KitCollection", b =>
                {
                    b.HasOne("SurveyStore.Modules.Collections.Domain.Collections.Entities.Kit", "Kit")
                        .WithMany()
                        .HasForeignKey("KitId");

                    b.HasOne("SurveyStore.Modules.Collections.Domain.Collections.Entities.Surveyor", "Surveyor")
                        .WithMany("KitCollections")
                        .HasForeignKey("SurveyorId");

                    b.Navigation("Kit");

                    b.Navigation("Surveyor");
                });

            modelBuilder.Entity("SurveyStore.Modules.Collections.Domain.Collections.Entities.Surveyor", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("KitCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
