@url = http://localhost:5000/equipment-module

@equipmentId = 0a6cb60f-b11e-4fac-b07a-3fe6ba007734

@kitId = 2d650bfa-fae0-4e30-b123-6096024410ab

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YThiNWU4NjYxNjg0N2U2OTJhYjFmMTFhMGU2M2MzYiIsInVuaXF1ZV9uYW1lIjoiNWE4YjVlODY2MTY4NDdlNjkyYWIxZjExYTBlNjNjM2IiLCJqdGkiOiJmNzdmY2UzYS04ZjExLTQyMjItYWVlYi1hMzY4ODc3Y2JmNWEiLCJpYXQiOiIxNzE1Mjg4NDcxMDIyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsInBlcm1pc3Npb25zIjpbInN0b3JlcyIsInVzZXJzIiwic3VydmV5b3JzIiwiZXF1aXBtZW50IiwiY29sbGVjdGlvbnMiLCJjYWxpYnJhdGlvbnMiLCJzYWdhIl0sIm5iZiI6MTcxNTI4ODQ3MSwiZXhwIjoxNzE1MzcxMjcxLCJpc3MiOiJzdXJ2ZXlzdG9yZSJ9.xu_A2aovhhP0GS2UHSDT-xu0wVY9yXMtXulSxqEbTOY
###
GET {{url}}

###
GET {{url}}/equipment/all

###
GET {{url}}/equipment/{{equipmentId}}
Authorization: Bearer {{accessToken}}

###
GET {{url}}/equipment
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "serialNumber": "ABC123"
}

###
POST {{url}}/equipment
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
        "brand": "Trimble",
        "model": "R12i",
        "description": "Lorem ipsum",
        "serialNumber": "XYZ123",
        "purchasedAt": "2023-01-01",
        //"accuracy": 1.0,
        //"maxRemoteDistance": 800
        "isActive": true
        //"screenSize": "",
        //"frequency": "",
//"offRoadMode": ""
}

###
POST {{url}}/equipment/total-station
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
        "brand": "Trimble",
        "model": "S5",
        "description": "Lorem ipsum",
        "serialNumber": "ABC1234",
        "purchasedAt": "2023-01-01",
        //"storeName": "TBH",
        "accuracy": 2.0,
        "maxRemoteDistance": 800
}

###
POST {{url}}/equipment/gnss
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
        "brand": "Trimble",
        "model": "R8",
        "description": "Lorem ipsum",
        "serialNumber": "XYZ1234",
        "purchasedAt": "2023-01-01",
        "isActive": true
}

###
POST {{url}}/equipment/field-controller
Content-Type: application/json

{
        "brand": "Trimble",
        "model": "TSC7",
        "description": "Lorem ipsum",
        "serialNumber": "QWE123",
        "purchasedAt": "2023-01-01",
        "calibrationDate": "2024-12-01",
        "screenSize": 7
}

###
GET {{url}}/kit/{{kitId}}
Authorization: Bearer {{accessToken}}

###
POST {{url}}/kit
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
        "brand": "Trimble",
        "model": "Tri300",
        "serialNumber": "45678",
        "purchasedAt": "2023-01-01"
}