@url = http://localhost:5000/equipment-module

@equipmentId = 51afc112-5c80-4657-a1c4-0f05ffa2045b

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MzAwYTA5MzJmYWU0MzJkOTYxMjIyNjkzMGM4ZGNlZSIsInVuaXF1ZV9uYW1lIjoiOTMwMGEwOTMyZmFlNDMyZDk2MTIyMjY5MzBjOGRjZWUiLCJqdGkiOiJjZWU2YTQ3Zi1mOGUwLTRkZjAtYjhmMy1mNmM3ZDQ0MTY2YzUiLCJpYXQiOiIxNzExNjY1OTU4MDAyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsInBlcm1pc3Npb25zIjpbInN0b3JlcyIsInVzZXJzIiwic3VydmV5b3JzIiwiZXF1aXBtZW50IiwiY29sbGVjdGlvbnMiXSwibmJmIjoxNzExNjY1OTU4LCJleHAiOjE3MTE3NDg3NTgsImlzcyI6InN1cnZleXN0b3JlIn0.Tj6bPtKTD-7_SyViVzZe-VenafgKPtlgx6E-IJ2FQ50
###
GET {{url}}

###
GET {{url}}/equipment/all

###
GET {{url}}/equipment/{{equipmentId}}
Authorization: Bearer {{accessToken}}

###
GET {{url}}/equipment
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "serialNumber": "ABC123"
}

###
POST {{url}}/equipment
Content-Type: application/json

{
        "brand": "Trimble",
        "model": "R12i",
        "description": "Lorem ipsum",
        "serialNumber": "XYZ123",
        "purchasedAt": "2023-01-01",
        "calibrationDate": "2024-12-01",
        //"accuracy": 1.0,
        //"maxRemoteDistance": 800
        "isActive": true
        //"screenSize": "",
        //"frequency": "",
        //"offRoadMode": ""
}

###
POST {{url}}/equipment/total-station
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
        "brand": "Trimble",
        "model": "S5",
        "description": "Lorem ipsum",
        "serialNumber": "ABC123",
        "purchasedAt": "2023-01-01",
        "calibrationDate": "2024-12-01",
        //"storeName": "TBH",
        "accuracy": 2.0,
        "maxRemoteDistance": 600
}

###
POST {{url}}/equipment/assign-store
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
        "serialNumber": "ABC1",
        "storeName": "TBH"
}

###
POST {{url}}/equipment/gnss
Content-Type: application/json

{
        "brand": "Trimble",
        "model": "R12i",
        "description": "Lorem ipsum",
        "serialNumber": "XYZ123",
        "purchasedAt": "2023-01-01",
        "isActive": true
}

###
POST {{url}}/equipment/field-controller
Content-Type: application/json

{
        "brand": "Trimble",
        "model": "TSC7",
        "description": "Lorem ipsum",
        "serialNumber": "QWE123",
        "purchasedAt": "2023-01-01",
        "calibrationDate": "2024-12-01",
        "screenSize": 7
}