@url = http://localhost:5000/calibrations-module
@serialNumber = XYZ123

###
GET {{url}}

###
GET {{url}}/calibrations/all

###
GET {{url}}/calibrations/due

###
GET {{url}}/calibrations/equipment/details

###
GET {{url}}/calibrations/equipment/{{serialNumber}}/details

###
POST {{url}}/calibrations/equipment/{{serialNumber}}/calibrate
Content-Type: application/json

{
    "calibrationDueDate": "2024-04-30",
    "certificateNumber": "XXX-YYY-345"
}