@url = http://localhost:5000/calibrations-module
@serialNumber = ABC123

###
GET {{url}}

###
GET {{url}}/calibrations/equipment/details

###
GET {{url}}/calibrations/equipment/{{serialNumber}}/details

###
POST {{url}}/calibrations/equipment/{{serialNumber}}/details
Content-Type: application/json

{
    "calibrationDueDate": "2024-05-20",
    "certificateNumber": "XXX-YYY-123"
}