@url = http://localhost:5000/calibrations-module
@serialNumber = ABC12333

###
GET {{url}}

###
GET {{url}}/calibrations/all

###
GET {{url}}/calibrations/due

###
POST {{url}}/calibrations/equipment/{{serialNumber}}/calibrate
Content-Type: application/json

{
    "calibrationDueDate": "2024-07-09",
    "certificateNumber": "XXX-YYY-345"
}