@url = http://localhost:5000/jobs-module


@surveyJobName = GAR
@surveyJobId = 5c8dca37-0355-4e45-b803-068ef9d0ebde

@surveyorEmail = user1@gmail.com
@surveyorEmail2 = user2@gmail.com

###
GET {{url}}

###
GET {{url}}/surveyJobs/free

###
GET {{url}}/surveyJobs/{{surveyJobId}}

###
GET {{url}}/surveyJobs/{{surveyJobName}}

###
GET {{url}}/surveyJobs
Content-Type: application/json

{
    "email": "{{surveyorEmail2}}"
}

###
POST {{url}}/surveyJobs
Content-Type: application/json

{
    "name": "GAR1",
    "briefIssued": "2024-05-27",
    "dueDate": "2024-06-26",
    "budget": "3000",
    "surveyType": "topo"
    //"documentLinks": ["http://photo1", "http://photo2"]
    //"surveyorEmails": ["{{surveyorEmail}}"]
}

###
PUT {{url}}/surveyJobs/{{surveyJobId}}/budget
Content-Type: application/json

{
    "budget": 90000
}

###
PUT {{url}}/surveyJobs/{{surveyJobId}}/surveyors
Content-Type: application/json

{
    //"surveyorEmails": ["{{surveyorEmail}}", "{{surveyorEmail2}}"]
    "surveyorEmails": ["{{surveyorEmail2}}"]
}

###
POST {{url}}/documents
Content-Type: application/json

{
    "documentType": "photo",
    "link": "http://photo3"
}