@url = http://localhost:5000/jobs-module


@surveyJobName = GAR3
@surveyJobId = 09fbea3b-fb88-49c0-8102-61952d393220

@surveyorEmail = user1@gmail.com
@surveyorEmail2 = user2@gmail.com

###
GET {{url}}

###
GET {{url}}/surveyJobs/free

###
GET {{url}}/surveyJobs/{{surveyJobId}}

###
GET {{url}}/surveyJobs/{{surveyJobName}}

###
GET {{url}}/surveyJobs
Content-Type: application/json

{
    "email": "{{surveyorEmail2}}"
}

###
POST {{url}}/surveyJobs
Content-Type: application/json

{
    "name": "GAR",
    "briefIssued": "2024-05-27",
    "dueDate": "2024-06-26",
    "budget": "30000",
    "surveyType": "topo",
    //"documentLinks": ["http://photo1", "http://photo2"]
    "surveyorEmails": ["{{surveyorEmail}}", "{{surveyorEmail2}}"]
    //"surveyorEmails": ["{{surveyorEmail}}"]
}

###
PUT {{url}}/surveyJobs/{{surveyJobId}}/budget
Content-Type: application/json

{
    "budget": 90000
}

###
PUT {{url}}/surveyJobs/{{surveyJobId}}/issue
Content-Type: application/json

{
    "issuedAt": "2024-06-09"
}

###
PUT {{url}}/surveyJobs/{{surveyJobId}}/surveyors
Content-Type: application/json

{
    //"surveyorEmails": ["{{surveyorEmail}}", "{{surveyorEmail2}}"]
    "surveyorEmails": ["{{surveyorEmail2}}"]
}

###
POST {{url}}/documents
Content-Type: application/json

{
    "documentType": "photo",
    "link": "http://photo3"
}