@url = http://localhost:5000/collections-module

@equipmentId = 939548a0-c124-4039-a65f-a1406622aee6

@storeId = 596f3a1b-a0a8-41ef-b460-20a8384053d1

###
GET {{url}}

###
GET {{url}}/collections

###
POST {{url}}/collections/equipment/{{equipmentId}}/assign-store
Content-Type: application/json

{
    "storeId": "{{storeId}}"
}

###
POST {{url}}/collections/equipment/{{equipmentId}}
Content-Type: application/json

{
    "collectionStoreId": "{{storeId}}"
}