@url = http://localhost:5000/collections-module

@equipmentId = 14f37f8d-5ebc-4123-a1d9-4e01451ed73f

@store1Id = 12996fdf-65ed-4e2a-8dde-e6b5609fe23c
@store2Id = 398e2129-71a2-4680-aa73-3f2cdaa5bdc0

@surveyorId1 = 4073370e-fb91-4cd5-8b8e-df09cb8ba726
@surveyorId2 = cfa0957d-d81a-4395-a5ac-d311fd001541

###
GET {{url}}

###
GET {{url}}/collections/equipment/all

###
GET {{url}}/collections/equipment/available

###
GET {{url}}/collections/equipment/{{surveyorId1}}/collected

###
POST {{url}}/collections/equipment/{{equipmentId}}/assign-store
Content-Type: application/json

{
    "storeId": "{{store2Id}}"
}

###
POST {{url}}/collections/equipment/{{equipmentId}}
Content-Type: application/json

{
    "collectionStoreId": "{{store2Id}}"
}

###
PUT {{url}}/collections/equipment/{{equipmentId}}/collect
Content-Type: application/json

{
    "surveyorId": "{{surveyorId1}}"
}

###
PUT {{url}}/collections/equipment/{{equipmentId}}/return
Content-Type: application/json

{
    "surveyorId": "{{surveyorId1}}",
    "returnStoreId": "{{store2Id}}"
}