@url = http://localhost:5000/collections-module

@equipmentId = 653286a2-6540-499a-ad6e-b966fe67899b

@storeId = f3bac81e-9766-41e1-a7fc-913fc68d82a8

@surveyorId = 0e00b6e1-8f55-44c0-a7ff-b777fd5e31d0

###
GET {{url}}

###
GET {{url}}/collections

###
GET {{url}}/collections/equipment/all

###
GET {{url}}/collections/equipment/available

###
POST {{url}}/collections/equipment/{{equipmentId}}/assign-store
Content-Type: application/json

{
    "storeId": "{{storeId}}"
}

###
POST {{url}}/collections/equipment/{{equipmentId}}
Content-Type: application/json

{
    "collectionStoreId": "{{storeId}}"
}

###
PUT {{url}}/collections/equipment/{{equipmentId}}/collect
Content-Type: application/json

{
    "surveyorId": "{{surveyorId}}"
}

###
PUT {{url}}/collections/equipment/{{equipmentId}}/return
Content-Type: application/json

{
    "surveyorId": "{{surveyorId}}",
    "returnStoreId": "{{storeId}}"
}