@url = http://localhost:5000/users-module

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZTAwYjZlMThmNTU0NGMwYTdmZmI3NzdmZDVlMzFkMCIsInVuaXF1ZV9uYW1lIjoiMGUwMGI2ZTE4ZjU1NDRjMGE3ZmZiNzc3ZmQ1ZTMxZDAiLCJqdGkiOiJkZDI1ODI2ZS0zOTQwLTQxMTItODhiYi03NjFiNThkODQ3M2MiLCJpYXQiOiIxNzEyNzgxNTI5ODk0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsInBlcm1pc3Npb25zIjpbInN0b3JlcyIsInVzZXJzIiwic3VydmV5b3JzIiwiZXF1aXBtZW50IiwiY29sbGVjdGlvbnMiXSwibmJmIjoxNzEyNzgxNTI5LCJleHAiOjE3MTI4NjQzMjksImlzcyI6InN1cnZleXN0b3JlIn0.z3PsixbnWjXzdfJ6Vbaui-Mosk82CJfGRV4HC6NdXcs

###
GET {{url}}

###
GET {{url}}/account/me
Authorization: Bearer {{accessToken}}

###
POST {{url}}/account/sign-up
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "secret",
    "role": "user",
    "claims": {"permissions": ["stores", "users", "surveyors", "equipment", "collections"]}

}

###
POST {{url}}/account/sign-in
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "secret"
}