@url = http://localhost:5000/users-module

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YThiNWU4NjYxNjg0N2U2OTJhYjFmMTFhMGU2M2MzYiIsInVuaXF1ZV9uYW1lIjoiNWE4YjVlODY2MTY4NDdlNjkyYWIxZjExYTBlNjNjM2IiLCJqdGkiOiI0OTY4Nzc3Mi00Y2JmLTQxMTEtOWY3Yy0yYWYwNjZhMWJlYjAiLCJpYXQiOiIxNzE1MTAzNzA3NjMwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsInBlcm1pc3Npb25zIjpbInN0b3JlcyIsInVzZXJzIiwic3VydmV5b3JzIiwiZXF1aXBtZW50IiwiY29sbGVjdGlvbnMiLCJjYWxpYnJhdGlvbnMiLCJzYWdhIl0sIm5iZiI6MTcxNTEwMzcwNywiZXhwIjoxNzE1MTg2NTA3LCJpc3MiOiJzdXJ2ZXlzdG9yZSJ9.kaedUUakqm0ZsxmVmZYB63Y9eS9Q-7IShcnQqvyeAPI

###
GET {{url}}

###
GET {{url}}/account/me
Authorization: Bearer {{accessToken}}

###
POST {{url}}/account/sign-up
Content-Type: application/json

{
    "email": "test2@gmail.com",
    "password": "secret",
    "role": "user",
    "claims": {"permissions": ["stores", "users", "surveyors", "equipment", "collections", "calibrations", "saga"]}

}

###
POST {{url}}/account/sign-in
Content-Type: application/json

{
    "email": "test2@gmail.com",
    "password": "secret"
}