@url = http://localhost:5000/stores-module

@storeId = 9b55bfb9-63c1-4532-9549-2cd31d1cc62c

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YThiNWU4NjYxNjg0N2U2OTJhYjFmMTFhMGU2M2MzYiIsInVuaXF1ZV9uYW1lIjoiNWE4YjVlODY2MTY4NDdlNjkyYWIxZjExYTBlNjNjM2IiLCJqdGkiOiIxYjRjMDNhNi01ZmZhLTRmMTUtYTk1ZS0zMGNjMjJjNmU2YTIiLCJpYXQiOiIxNzE0NDgzNDg0MTUyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsInBlcm1pc3Npb25zIjpbInN0b3JlcyIsInVzZXJzIiwic3VydmV5b3JzIiwiZXF1aXBtZW50IiwiY29sbGVjdGlvbnMiLCJjYWxpYnJhdGlvbnMiLCJzYWdhIl0sIm5iZiI6MTcxNDQ4MzQ4NCwiZXhwIjoxNzE0NTY2Mjg0LCJpc3MiOiJzdXJ2ZXlzdG9yZSJ9.82uR5e3dkzK_KWiEMyiDki587X9Zjg0E6A5CFS5bOZY
###
GET {{url}}

###
GET {{url}}/stores

###
GET {{url}}/stores/{{storeId}}S

###
POST {{url}}/stores
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "TBH",
    "location": "TBH",
    "openingTime": "2020-01-01T07:00:00",
    "closingTime": "2020-01-01T17:00:00"
}

###
PUT {{url}}/stores/{{storeId}}
Content-Type: application/json

{
    "openingTime": "2020-01-01T07:00:00",
    "closingTime": "2020-01-01T18:00:00"
}

###
DELETE {{url}}/stores/{{storeId}}
Authorization: Bearer {{accessToken}}