@url = http://localhost:5000/stores-module

@storeId = 83eeae8e-e0a3-4551-b254-b870cb048b00

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MGM3YjI5ZDUwN2I0OTMwOWIwNDUzMjAxMTYxOTc3ZCIsInVuaXF1ZV9uYW1lIjoiNDBjN2IyOWQ1MDdiNDkzMDliMDQ1MzIwMTE2MTk3N2QiLCJqdGkiOiJlN2FiOWI5Ni02NzI4LTQxMmYtYTRhYy05MzE5ODIxMWU1YmIiLCJpYXQiOiIxNzEzOTM2NjY0NzcyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsInBlcm1pc3Npb25zIjpbInN0b3JlcyIsInVzZXJzIiwic3VydmV5b3JzIiwiZXF1aXBtZW50IiwiY29sbGVjdGlvbnMiLCJjYWxpYnJhdGlvbnMiLCJzYWdhIl0sIm5iZiI6MTcxMzkzNjY2NCwiZXhwIjoxNzE0MDE5NDY0LCJpc3MiOiJzdXJ2ZXlzdG9yZSJ9.qK_iEsCP0EPmF5uP8ZA4S0jxPo1nv1kkjSBFRME0a88

###
GET {{url}}

###
GET {{url}}/stores

###
GET {{url}}/stores/{{storeId}}

###
POST {{url}}/stores
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "VIA",
    "location": "Bilsthorpe",
    "openingTime": "2020-01-01T07:00:00",
    "closingTime": "2020-01-01T17:00:00"
}

###
PUT {{url}}/stores/{{storeId}}
Content-Type: application/json

{
    "openingTime": "2020-01-01T07:00:00",
    "closingTime": "2020-01-01T18:00:00"
}

###
DELETE {{url}}/stores/{{storeId}}
Authorization: Bearer {{accessToken}}