@url = http://localhost:5000/stores-module

@storeId = 83eeae8e-e0a3-4551-b254-b870cb048b00

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMWIyMWZhNmI3MzM0NjNlOWE2NzQ5ODRkZThkZDEyZCIsInVuaXF1ZV9uYW1lIjoiYTFiMjFmYTZiNzMzNDYzZTlhNjc0OTg0ZGU4ZGQxMmQiLCJqdGkiOiI2Y2IxYWFkOS02NWE2LTRmZGYtYTI4YS1kODhhYTEyNzUzNzkiLCJpYXQiOiIxNzEzODE3OTQyOTc4IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsInBlcm1pc3Npb25zIjpbInN0b3JlcyIsInVzZXJzIiwic3VydmV5b3JzIiwiZXF1aXBtZW50IiwiY29sbGVjdGlvbnMiLCJjYWxpYnJhdGlvbnMiLCJzYWdhIl0sIm5iZiI6MTcxMzgxNzk0MiwiZXhwIjoxNzEzOTAwNzQyLCJpc3MiOiJzdXJ2ZXlzdG9yZSJ9.Stn0V1HL8ADs5M3cJ5algXiQb1Ui17idyuCmJR5muJM

###
GET {{url}}

###
GET {{url}}/stores

###
GET {{url}}/stores/{{storeId}}

###
POST {{url}}/stores
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "VIA",
    "location": "Bilsthorpe",
    "openingTime": "2020-01-01T07:00:00",
    "closingTime": "2020-01-01T17:00:00"
}

###
PUT {{url}}/stores/{{storeId}}
Content-Type: application/json

{
    "openingTime": "2020-01-01T07:00:00",
    "closingTime": "2020-01-01T18:00:00"
}

###
DELETE {{url}}/stores/{{storeId}}
Authorization: Bearer {{accessToken}}